/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 서버 상태 확인 */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 정상 */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /** @example ok */
                            readonly status: string;
                            /** @example gang-saeroi-api */
                            readonly service: string;
                            /** @example 강 새로이 */
                            readonly name: string;
                        };
                    };
                };
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/game/config": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 게임 설정 조회 */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 하천, 정책, 등급, 설문 선택지 */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["GameConfig"];
                    };
                };
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/simulations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 정책 조합 계산 */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["SimulationRequest"];
                };
            };
            readonly responses: {
                /** @description 서버가 계산한 결과 */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["SimulationResult"];
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 413: components["responses"]["PayloadTooLarge"];
                readonly 415: components["responses"]["UnsupportedMediaType"];
                readonly 500: components["responses"]["InternalServerError"];
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/responses": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * 익명 참여 결과 저장
         * @description 계산 결과 필드는 받지 않으며 서버가 정책 ID로 다시 계산합니다.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["SubmissionRequest"];
                };
            };
            readonly responses: {
                /** @description 저장 완료 */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /** Format: uuid */
                            readonly id: string;
                            /** Format: date-time */
                            readonly createdAt: string;
                            readonly result: components["schemas"]["SimulationResult"];
                        };
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 413: components["responses"]["PayloadTooLarge"];
                readonly 415: components["responses"]["UnsupportedMediaType"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["DatabaseUnavailable"];
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 시민 참여 통계 조회 */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 전체, 하천별, 정책별 집계와 익명 의견 */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Statistics"];
                    };
                };
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["DatabaseUnavailable"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/candidate/report": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * 후보자용 정책 리포트 데이터 조회
         * @description 날짜 필터는 저장된 UTC 날짜를 기준으로 시작일과 종료일을 모두 포함합니다.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly riverId?: components["parameters"]["CandidateRiverId"];
                    readonly district?: components["parameters"]["CandidateDistrict"];
                    /** @description UTC 기준 시작일이며 해당 날짜를 포함합니다. */
                    readonly from?: components["parameters"]["CandidateFromDate"];
                    /** @description UTC 기준 종료일이며 해당 날짜를 포함합니다. */
                    readonly to?: components["parameters"]["CandidateToDate"];
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 인쇄용 화면에 사용할 리포트 집계 */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CandidateReport"];
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["DatabaseUnavailable"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/candidate/comments": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * 후보자용 시민 의견 목록 조회
         * @description 내용이 있는 익명 의견만 필터링해 페이지 단위로 제공합니다.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly riverId?: components["parameters"]["CandidateRiverId"];
                    readonly district?: components["parameters"]["CandidateDistrict"];
                    /** @description UTC 기준 시작일이며 해당 날짜를 포함합니다. */
                    readonly from?: components["parameters"]["CandidateFromDate"];
                    /** @description UTC 기준 종료일이며 해당 날짜를 포함합니다. */
                    readonly to?: components["parameters"]["CandidateToDate"];
                    readonly page?: number;
                    readonly pageSize?: number;
                    readonly sort?: "latest" | "oldest";
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 필터와 정렬이 적용된 의견 페이지 */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CandidateCommentsPage"];
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["DatabaseUnavailable"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly ErrorEnvelope: {
            readonly error: {
                readonly code: string;
                readonly message: string;
                readonly details: readonly {
                    readonly [key: string]: unknown;
                }[];
                readonly requestId: string;
            };
        };
        /** @description 정책이 두 개 이상이고 eventChoice를 생략하면 event.status가 PENDING으로 반환됩니다. */
        readonly SimulationRequest: {
            /** @enum {string} */
            readonly riverId: "dongcheon" | "goejeongcheon" | "oncheoncheon";
            readonly policyIds: readonly ("sewer" | "treatment" | "sourceBlock" | "ecology" | "sensor" | "monitoring" | "walking")[];
            /** @enum {string} */
            readonly eventChoice?: "INVESTIGATE" | "WAIT";
        };
        /** @description 정책을 두 개 이상 선택한 최종 제출에는 eventChoice가 필요합니다. */
        readonly SubmissionRequest: {
            /** @enum {string} */
            readonly riverId: "dongcheon" | "goejeongcheon" | "oncheoncheon";
            readonly policyIds: readonly ("sewer" | "treatment" | "sourceBlock" | "ecology" | "sensor" | "monitoring" | "walking")[];
            /** @enum {string} */
            readonly eventChoice?: "INVESTIGATE" | "WAIT";
            /** @enum {string} */
            readonly topPriority: "source_control" | "treatment" | "sensor" | "ecology" | "walking" | "citizen_monitoring";
            /** @enum {string} */
            readonly district: "geumjeong" | "dongnae" | "busanjin" | "saha" | "other" | "prefer_not";
            /** @description 이름, 전화번호, 이메일, 주민등록번호, 정확한 주소와 HTML 태그를 포함할 수 없습니다. */
            readonly comment?: string;
            /** @enum {boolean} */
            readonly consentToAggregate: true;
        };
        readonly Grade: {
            /** @enum {string} */
            readonly symbol: "Ia" | "Ib" | "II" | "III" | "IV" | "V" | "VI";
            readonly name: string;
            readonly label: string;
            readonly maxBod?: number | null;
            readonly level: number;
        };
        readonly Badge: {
            /** @enum {string} */
            readonly id: "GOOD_ACHIEVED" | "ONE_MG_PERFECT" | "ECOLOGY_RECOVERY" | "CITIZEN_EMPATHY" | "SMART_MANAGEMENT" | "BUDGET_SAVER";
            readonly name: string;
            readonly description: string;
        };
        readonly Recommendation: {
            /** @enum {string} */
            readonly policyId: "sewer" | "treatment" | "sourceBlock" | "ecology";
            readonly policyName: string;
            readonly cost: number;
            readonly reason: string;
            readonly expectedFinalBod: number;
            /** @enum {string} */
            readonly expectedFinalGrade: "Ia" | "Ib" | "II" | "III" | "IV" | "V" | "VI";
            readonly expectedFinalGradeLabel: string;
            /** @enum {string} */
            readonly expectedResultStatus: "TRY_AGAIN" | "MISSION_COMPLETE" | "PERFECT_CLEAR";
            readonly expectedMissionSuccess: boolean;
            readonly expectedPerfectClear: boolean;
            readonly expectedRemainingBudget: number;
        };
        readonly SimulationResult: {
            readonly river: {
                readonly id?: string;
                readonly name?: string;
            };
            readonly character: string;
            readonly initialBod: number;
            readonly finalBod: number;
            readonly bodReduction?: number;
            readonly initialGrade: components["schemas"]["Grade"];
            readonly finalGrade: components["schemas"]["Grade"];
            readonly gradeImprovement?: number;
            /** @enum {string} */
            readonly resultStatus: "TRY_AGAIN" | "MISSION_COMPLETE" | "PERFECT_CLEAR";
            readonly resultTitle: string;
            readonly resultMessage: string;
            readonly missionSuccess: boolean;
            readonly perfectClear: boolean;
            readonly remainingBodToMission?: number;
            readonly selectedPolicies?: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly policyOrder: readonly string[];
            readonly budgetUsed: number;
            readonly remainingBudget: number;
            readonly scores: {
                readonly ecology?: number;
                readonly citizen?: number;
                readonly monitoring?: number;
            };
            readonly event: components["schemas"]["EventResult"];
            readonly selectedPledgeAreas?: readonly ("CLEAN UP" | "SMART UP" | "WALK UP")[];
            readonly pledgeMatchRate?: number;
            readonly badges: readonly components["schemas"]["Badge"][];
            readonly strengths: readonly string[];
            readonly recommendations: readonly components["schemas"]["Recommendation"][];
            /** @enum {boolean} */
            readonly isDemoData?: true;
            readonly disclaimer?: string;
        } & {
            readonly [key: string]: unknown;
        };
        readonly GameConfig: {
            /** @example 강 새로이 */
            readonly serviceName: string;
            readonly version: string;
            /** @example 100 */
            readonly maxBudget: number;
            readonly grades: readonly components["schemas"]["Grade"][];
            readonly rivers: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly policies: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly events: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly badgeDefinitions: readonly components["schemas"]["Badge"][];
            readonly resultStatuses: readonly {
                /** @enum {string} */
                readonly id: "TRY_AGAIN" | "MISSION_COMPLETE" | "PERFECT_CLEAR";
                readonly title: string;
                readonly message: string;
            }[];
            readonly priorities: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly districts: readonly {
                readonly [key: string]: unknown;
            }[];
            /** @enum {boolean} */
            readonly isDemoData: true;
        } & {
            readonly [key: string]: unknown;
        };
        readonly Statistics: {
            readonly totalParticipants: number;
            readonly missionSuccessRate: number;
            readonly perfectClearRate: number;
            readonly averageGradeImprovement: number;
            readonly riverParticipation: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly policySelection: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly eventStatistics: components["schemas"]["EventStatistics"];
            readonly commentKeywordAnalysis: components["schemas"]["CommentKeywordAnalysis"];
            readonly comments: readonly {
                readonly [key: string]: unknown;
            }[];
        } & {
            readonly [key: string]: unknown;
        };
        readonly EventResult: {
            /** @enum {string} */
            readonly id: "DOWNSTREAM_ODOR_SURGE";
            readonly name: string;
            /** @enum {integer} */
            readonly triggerPolicyCount: 2;
            /** @enum {string} */
            readonly status: "NOT_TRIGGERED" | "PENDING" | "RESOLVED";
            /** @enum {string|null} */
            readonly choice: "INVESTIGATE" | "WAIT" | null;
            /** @enum {integer} */
            readonly cost: 0 | 5;
            readonly scoreEffects: {
                readonly ecology: number;
                readonly citizen: number;
                readonly monitoring: number;
            };
            readonly sensorAssisted: boolean;
            readonly message: string | null;
            /** @enum {string|null} */
            readonly temporaryCharacterMood: "WORRIED" | null;
        };
        readonly EventStatistics: {
            /** @enum {string} */
            readonly eventId: "DOWNSTREAM_ODOR_SURGE";
            readonly eligibleParticipants: number;
            readonly respondedParticipants: number;
            readonly responseRate: number;
            readonly choices: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly sensorAssistedInvestigations: {
                readonly count: number;
                readonly rate: number;
            };
        };
        readonly CommentKeywordCategory: {
            /** @enum {string} */
            readonly id: "ODOR" | "POLLUTION_SOURCE" | "DATA_DISCLOSURE" | "ECOLOGY_RESTORATION" | "WALKING_AMENITIES" | "OTHER";
            readonly name: string;
            readonly count: number;
            readonly rate: number;
        };
        readonly CommentKeywordAnalysis: {
            readonly totalComments: number;
            /** @enum {string} */
            readonly classificationMode: "SINGLE_PRIMARY";
            readonly dictionaryVersion: string;
            readonly categories: readonly components["schemas"]["CommentKeywordCategory"][];
            readonly topCategories: readonly components["schemas"]["CommentKeywordCategory"][];
        };
        readonly CandidateFilters: {
            readonly riverId: string | null;
            readonly district: string | null;
            /** Format: date */
            readonly from: string | null;
            /** Format: date */
            readonly to: string | null;
        };
        readonly CandidateComment: {
            /** Format: uuid */
            readonly id: string;
            readonly riverId: string;
            readonly riverName: string;
            readonly district: string;
            readonly districtName: string;
            readonly topPriority: string;
            readonly topPriorityName: string;
            readonly comment: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        readonly CandidateReport: {
            readonly title: string;
            readonly period: {
                /** Format: date-time */
                readonly from: string | null;
                /** Format: date-time */
                readonly to: string | null;
            };
            readonly filters: components["schemas"]["CandidateFilters"];
            readonly summary: {
                readonly [key: string]: unknown;
            };
            readonly policySelection: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly topPriorities: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly pledgeAreaSelection: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly eventStatistics: components["schemas"]["EventStatistics"];
            readonly commentKeywordAnalysis: components["schemas"]["CommentKeywordAnalysis"];
            readonly perRiver: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly prioritiesByRiver: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly prioritiesByDistrict: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly comments: readonly components["schemas"]["CandidateComment"][];
            readonly methodology: {
                readonly [key: string]: unknown;
            };
            /** @enum {boolean} */
            readonly isDemoData: true;
        } & {
            readonly [key: string]: unknown;
        };
        readonly CandidateCommentsPage: {
            readonly items: readonly components["schemas"]["CandidateComment"][];
            readonly pagination: {
                readonly page: number;
                readonly pageSize: number;
                readonly totalItems: number;
                readonly totalPages: number;
                readonly hasNext: boolean;
                readonly hasPrevious: boolean;
            };
            /** @enum {string} */
            readonly sort: "latest" | "oldest";
            readonly filters: components["schemas"]["CandidateFilters"];
            /** @enum {boolean} */
            readonly isDemoData: true;
        };
    };
    responses: {
        /** @description 입력값 오류 */
        readonly ValidationError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": {
                    readonly error: {
                        /** @enum {string} */
                        readonly code: "VALIDATION_ERROR" | "PERSONAL_INFORMATION_NOT_ALLOWED";
                        readonly message: string;
                        readonly details: readonly {
                            readonly field?: string;
                            readonly reason?: string;
                        }[];
                        readonly requestId: string;
                    };
                };
            };
        };
        /** @description 공유 데이터베이스 일시 장애 */
        readonly DatabaseUnavailable: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": {
                    readonly error: {
                        /** @enum {string} */
                        readonly code: "DATABASE_UNAVAILABLE";
                        readonly message: string;
                        readonly details: readonly unknown[];
                        readonly requestId: string;
                    };
                };
            };
        };
        /** @description 지원하지 않는 HTTP 메서드 */
        readonly MethodNotAllowed: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 요청 본문 크기 제한 초과 */
        readonly PayloadTooLarge: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description application/json이 아닌 요청 */
        readonly UnsupportedMediaType: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 예상하지 못한 서버 오류 */
        readonly InternalServerError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        readonly CandidateRiverId: "dongcheon" | "goejeongcheon" | "oncheoncheon";
        readonly CandidateDistrict: "geumjeong" | "dongnae" | "busanjin" | "saha" | "other" | "prefer_not";
        /** @description UTC 기준 시작일이며 해당 날짜를 포함합니다. */
        readonly CandidateFromDate: string;
        /** @description UTC 기준 종료일이며 해당 날짜를 포함합니다. */
        readonly CandidateToDate: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
