/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 서버 상태 확인 */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 정상 */
                readonly 200: {
                    headers: {
                        readonly "X-Request-ID": components["headers"]["RequestId"];
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/game/config": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 게임 설정 조회 */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 하천, 정책, 등급, 설문 선택지 */
                readonly 200: {
                    headers: {
                        readonly "X-Request-ID": components["headers"]["RequestId"];
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["GameConfig"];
                    };
                };
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/simulations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 정책 조합 계산 */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["SimulationRequest"];
                };
            };
            readonly responses: {
                /** @description 서버가 계산한 결과 */
                readonly 200: {
                    headers: {
                        readonly "X-Request-ID": components["headers"]["RequestId"];
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["SimulationResult"];
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 413: components["responses"]["PayloadTooLarge"];
                readonly 415: components["responses"]["UnsupportedMediaType"];
                readonly 500: components["responses"]["InternalServerError"];
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/responses": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * 익명 참여 결과 저장
         * @description 계산 결과 필드는 받지 않으며 서버가 정책 ID로 다시 계산합니다.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["SubmissionRequest"];
                };
            };
            readonly responses: {
                /** @description 저장 완료 */
                readonly 201: {
                    headers: {
                        readonly "X-Request-ID": components["headers"]["RequestId"];
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["SubmissionResponse"];
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 413: components["responses"]["PayloadTooLarge"];
                readonly 415: components["responses"]["UnsupportedMediaType"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["DatabaseUnavailable"];
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 시민 참여 통계 조회 */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 전체, 하천별, 정책별 집계와 익명 의견 */
                readonly 200: {
                    headers: {
                        readonly "X-Request-ID": components["headers"]["RequestId"];
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Statistics"];
                    };
                };
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["DatabaseUnavailable"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/candidate/report": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * 후보자용 정책 리포트 데이터 조회
         * @description 날짜 필터는 저장된 UTC 날짜를 기준으로 시작일과 종료일을 모두 포함합니다.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly riverId?: components["parameters"]["CandidateRiverId"];
                    readonly district?: components["parameters"]["CandidateDistrict"];
                    /** @description UTC 기준 시작일이며 해당 날짜를 포함합니다. */
                    readonly from?: components["parameters"]["CandidateFromDate"];
                    /** @description UTC 기준 종료일이며 해당 날짜를 포함합니다. */
                    readonly to?: components["parameters"]["CandidateToDate"];
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 인쇄용 화면에 사용할 리포트 집계 */
                readonly 200: {
                    headers: {
                        readonly "X-Request-ID": components["headers"]["RequestId"];
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CandidateReport"];
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 401: components["responses"]["AuthenticationRequired"];
                readonly 403: components["responses"]["AccessDenied"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["ServiceUnavailable"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/candidate/comments": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * 후보자용 시민 의견 목록 조회
         * @description 내용이 있는 익명 의견만 필터링해 페이지 단위로 제공합니다.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly riverId?: components["parameters"]["CandidateRiverId"];
                    readonly district?: components["parameters"]["CandidateDistrict"];
                    /** @description UTC 기준 시작일이며 해당 날짜를 포함합니다. */
                    readonly from?: components["parameters"]["CandidateFromDate"];
                    /** @description UTC 기준 종료일이며 해당 날짜를 포함합니다. */
                    readonly to?: components["parameters"]["CandidateToDate"];
                    readonly page?: number;
                    readonly pageSize?: number;
                    readonly sort?: "latest" | "oldest";
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description 필터와 정렬이 적용된 의견 페이지 */
                readonly 200: {
                    headers: {
                        readonly "X-Request-ID": components["headers"]["RequestId"];
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CandidateCommentsPage"];
                    };
                };
                readonly 400: components["responses"]["ValidationError"];
                readonly 401: components["responses"]["AuthenticationRequired"];
                readonly 403: components["responses"]["AccessDenied"];
                readonly 405: components["responses"]["MethodNotAllowed"];
                readonly 500: components["responses"]["InternalServerError"];
                readonly 503: components["responses"]["ServiceUnavailable"];
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        readonly RiverId: "dongcheon" | "goejeongcheon" | "oncheoncheon";
        /** @enum {string} */
        readonly PolicyId: "sewer" | "treatment" | "sourceBlock" | "ecology" | "sensor" | "monitoring" | "walking";
        /** @enum {string} */
        readonly DirectPolicyId: "sewer" | "treatment" | "sourceBlock" | "ecology";
        /** @enum {string} */
        readonly EventChoiceId: "INVESTIGATE" | "WAIT";
        /** @enum {string} */
        readonly TopPriorityId: "source_control" | "treatment" | "sensor" | "ecology" | "walking" | "citizen_monitoring";
        /** @enum {string} */
        readonly DistrictId: "geumjeong" | "dongnae" | "busanjin" | "saha" | "other" | "prefer_not";
        /** @enum {string} */
        readonly PledgeArea: "CLEAN UP" | "SMART UP" | "WALK UP";
        /** @enum {string} */
        readonly GradeSymbol: "Ia" | "Ib" | "II" | "III" | "IV" | "V" | "VI";
        /** @enum {string} */
        readonly ResultStatus: "TRY_AGAIN" | "MISSION_COMPLETE" | "PERFECT_CLEAR";
        /** @enum {string|null} */
        readonly CompletionReason: "WATER_GOAL" | "BUDGET_EXHAUSTED" | null;
        /** @enum {string} */
        readonly PlayerProfileId: "WATER_QUALITY" | "ECOLOGY" | "CITIZEN" | "SMART_MANAGEMENT" | "BALANCED";
        /** @enum {string} */
        readonly PlayerProfileMetric: "waterQuality" | "ecology" | "citizen" | "monitoring" | "balanced";
        readonly ErrorDetail: {
            readonly field: string;
            readonly reason: string;
            readonly allowed?: readonly string[];
        };
        readonly ErrorEnvelope: {
            readonly error: {
                /** @enum {string} */
                readonly code: "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "VALIDATION_ERROR" | "PERSONAL_INFORMATION_NOT_ALLOWED" | "DATABASE_UNAVAILABLE" | "CANDIDATE_AUTH_REQUIRED" | "CANDIDATE_ACCESS_DENIED" | "CANDIDATE_AUTH_UNAVAILABLE" | "INTERNAL_SERVER_ERROR" | "UNSUPPORTED_MEDIA_TYPE" | "INVALID_LENGTH" | "EMPTY_BODY" | "PAYLOAD_TOO_LARGE" | "INVALID_JSON";
                readonly message: string;
                readonly details: readonly components["schemas"]["ErrorDetail"][];
                readonly requestId: string;
            };
        };
        readonly HealthResponse: {
            /** @enum {string} */
            readonly status: "ok";
            /** @enum {string} */
            readonly service: "gang-saeroi-api";
            /** @enum {string} */
            readonly name: "강 새로이";
        };
        /** @description 정책이 두 개 이상이고 eventChoice를 생략하면 event.status가 PENDING으로 반환됩니다. */
        readonly SimulationRequest: {
            readonly riverId: components["schemas"]["RiverId"];
            readonly policyIds: readonly components["schemas"]["PolicyId"][];
            readonly eventChoice?: components["schemas"]["EventChoiceId"];
        };
        /** @description 정책을 두 개 이상 선택한 최종 제출에는 eventChoice가 필요합니다. */
        readonly SubmissionRequest: {
            readonly riverId: components["schemas"]["RiverId"];
            readonly policyIds: readonly components["schemas"]["PolicyId"][];
            readonly eventChoice?: components["schemas"]["EventChoiceId"];
            readonly topPriority: components["schemas"]["TopPriorityId"];
            readonly district: components["schemas"]["DistrictId"];
            /** @description 이름, 전화번호, 이메일, 주민등록번호, 정확한 주소와 HTML 태그를 포함할 수 없습니다. */
            readonly comment?: string;
            /** @enum {boolean} */
            readonly consentToAggregate: true;
        };
        readonly Grade: {
            readonly symbol: components["schemas"]["GradeSymbol"];
            readonly name: string;
            readonly label: string;
            readonly maxBod: number | null;
            readonly level: number;
        };
        readonly ScoreEffects: {
            readonly ecology: number;
            readonly citizen: number;
            readonly monitoring: number;
        };
        readonly Policy: {
            readonly id: components["schemas"]["PolicyId"];
            readonly name: string;
            readonly cost: number;
            readonly scoreEffects: components["schemas"]["ScoreEffects"];
            readonly pledgeArea: components["schemas"]["PledgeArea"];
            readonly directlyReducesBod: boolean;
        };
        readonly PolicyEffects: {
            readonly sewer: number;
            readonly treatment: number;
            readonly sourceBlock: number;
            readonly ecology: number;
        };
        readonly River: {
            readonly id: components["schemas"]["RiverId"];
            readonly name: string;
            readonly character: string;
            readonly initialBod: number;
            readonly initialGrade: components["schemas"]["Grade"];
            /** @enum {string} */
            readonly difficulty: "hard" | "normal" | "easy";
            readonly policyEffects: components["schemas"]["PolicyEffects"];
            /** @enum {boolean} */
            readonly isDemoData: true;
        };
        readonly Badge: {
            /** @enum {string} */
            readonly id: "GOOD_ACHIEVED" | "ONE_MG_PERFECT" | "ECOLOGY_RECOVERY" | "CITIZEN_EMPATHY" | "SMART_MANAGEMENT" | "BUDGET_SAVER";
            readonly name: string;
            readonly description: string;
        };
        readonly ResultPresentation: {
            readonly id: components["schemas"]["ResultStatus"];
            readonly title: string;
            readonly message: string;
        };
        readonly NamedPriority: {
            readonly id: components["schemas"]["TopPriorityId"];
            readonly name: string;
        };
        readonly NamedDistrict: {
            readonly id: components["schemas"]["DistrictId"];
            readonly name: string;
        };
        readonly SensorVariant: {
            /** @enum {string} */
            readonly requiredPolicyId: "sensor";
            /** @enum {integer} */
            readonly cost: 0;
            readonly scoreEffects: components["schemas"]["ScoreEffects"];
        };
        readonly InvestigateEventChoice: {
            /** @enum {string} */
            readonly id: "INVESTIGATE";
            readonly name: string;
            /** @enum {integer} */
            readonly baseCost: 5;
            readonly baseScoreEffects: components["schemas"]["ScoreEffects"];
            readonly sensorVariant: components["schemas"]["SensorVariant"];
        };
        readonly WaitEventChoice: {
            /** @enum {string} */
            readonly id: "WAIT";
            readonly name: string;
            /** @enum {integer} */
            readonly baseCost: 0;
            readonly baseScoreEffects: components["schemas"]["ScoreEffects"];
            /** @enum {string} */
            readonly temporaryCharacterMood: "WORRIED";
        };
        readonly GameEvent: {
            /** @enum {string} */
            readonly id: "DOWNSTREAM_ODOR_SURGE";
            readonly name: string;
            readonly description: string;
            /** @enum {integer} */
            readonly triggerPolicyCount: 2;
            readonly choices: readonly (components["schemas"]["InvestigateEventChoice"] | components["schemas"]["WaitEventChoice"])[];
        };
        readonly CommentRules: {
            /** @enum {integer} */
            readonly maxLength: 200;
            readonly privacyNotice: string;
            /** @enum {boolean} */
            readonly collectsPersonalInformation: false;
        };
        readonly GameConfig: {
            /** @enum {string} */
            readonly serviceName: "강 새로이";
            readonly version: string;
            /** @enum {integer} */
            readonly maxBudget: 100;
            /** @enum {number} */
            readonly minimumBod: 0.8;
            /** @enum {integer} */
            readonly baseScore: 30;
            /** @enum {number} */
            readonly successThresholdBod: 2;
            /** @enum {number} */
            readonly perfectThresholdBod: 1;
            readonly grades: readonly components["schemas"]["Grade"][];
            readonly rivers: readonly components["schemas"]["River"][];
            readonly policies: readonly components["schemas"]["Policy"][];
            readonly events: readonly components["schemas"]["GameEvent"][];
            readonly badgeDefinitions: readonly components["schemas"]["Badge"][];
            readonly resultStatuses: readonly components["schemas"]["ResultPresentation"][];
            readonly priorities: readonly components["schemas"]["NamedPriority"][];
            readonly districts: readonly components["schemas"]["NamedDistrict"][];
            readonly commentRules: components["schemas"]["CommentRules"];
            /** @enum {boolean} */
            readonly isDemoData: true;
            readonly demoDataNotice: string;
            readonly disclaimer: string;
        };
        readonly RiverIdentity: {
            readonly id: components["schemas"]["RiverId"];
            readonly name: string;
        };
        readonly SimulationScores: {
            readonly ecology: number;
            readonly citizen: number;
            readonly monitoring: number;
        };
        readonly CompletionState: {
            readonly canFinish: boolean;
            readonly reason: components["schemas"]["CompletionReason"];
            readonly budgetExhausted: boolean;
        };
        readonly PlayerProfileScores: {
            readonly waterQuality: number;
            readonly ecology: number;
            readonly citizen: number;
            readonly monitoring: number;
        };
        readonly PlayerProfile: {
            readonly id: components["schemas"]["PlayerProfileId"];
            readonly name: string;
            readonly description: string;
            readonly primaryMetric: components["schemas"]["PlayerProfileMetric"];
            readonly scores: components["schemas"]["PlayerProfileScores"];
        };
        readonly Recommendation: {
            readonly policyId: components["schemas"]["DirectPolicyId"];
            readonly policyName: string;
            readonly cost: number;
            readonly reason: string;
            readonly expectedFinalBod: number;
            readonly expectedFinalGrade: components["schemas"]["GradeSymbol"];
            readonly expectedFinalGradeLabel: string;
            readonly expectedResultStatus: components["schemas"]["ResultStatus"];
            readonly expectedMissionSuccess: boolean;
            readonly expectedPerfectClear: boolean;
            readonly expectedRemainingBudget: number;
        };
        readonly EventResult: {
            /** @enum {string} */
            readonly id: "DOWNSTREAM_ODOR_SURGE";
            readonly name: string;
            /** @enum {integer} */
            readonly triggerPolicyCount: 2;
            /** @enum {string} */
            readonly status: "NOT_TRIGGERED" | "PENDING" | "RESOLVED";
            /** @enum {string|null} */
            readonly choice: "INVESTIGATE" | "WAIT" | null;
            /** @enum {integer} */
            readonly cost: 0 | 5;
            readonly scoreEffects: components["schemas"]["ScoreEffects"];
            readonly sensorAssisted: boolean;
            readonly message: string | null;
            /** @enum {string|null} */
            readonly temporaryCharacterMood: "WORRIED" | null;
        };
        readonly SimulationResult: {
            readonly river: components["schemas"]["RiverIdentity"];
            readonly character: string;
            readonly initialBod: number;
            readonly finalBod: number;
            readonly bodReduction: number;
            readonly initialGrade: components["schemas"]["Grade"];
            readonly finalGrade: components["schemas"]["Grade"];
            readonly gradeImprovement: number;
            readonly resultStatus: components["schemas"]["ResultStatus"];
            readonly resultTitle: string;
            readonly resultMessage: string;
            readonly missionSuccess: boolean;
            readonly perfectClear: boolean;
            readonly remainingBodToMission: number;
            readonly selectedPolicies: readonly components["schemas"]["Policy"][];
            readonly policyOrder: readonly components["schemas"]["PolicyId"][];
            readonly budgetUsed: number;
            readonly remainingBudget: number;
            readonly scores: components["schemas"]["SimulationScores"];
            readonly event: components["schemas"]["EventResult"];
            readonly selectedPledgeAreas: readonly components["schemas"]["PledgeArea"][];
            readonly pledgeMatchRate: number;
            readonly badges: readonly components["schemas"]["Badge"][];
            readonly strengths: readonly string[];
            readonly recommendations: readonly components["schemas"]["Recommendation"][];
            readonly completion: components["schemas"]["CompletionState"];
            readonly playerProfile: components["schemas"]["PlayerProfile"];
            /** @enum {boolean} */
            readonly isDemoData: true;
            readonly disclaimer: string;
        };
        readonly SubmissionResponse: {
            /** Format: uuid */
            readonly id: string;
            /** Format: date-time */
            readonly createdAt: string;
            readonly result: components["schemas"]["SimulationResult"];
        };
        readonly RateItem: {
            readonly id: string;
            readonly name: string;
            readonly count: number;
            readonly rate: number;
        };
        readonly PledgeAreaRateItem: {
            readonly area: components["schemas"]["PledgeArea"];
            readonly count: number;
            readonly rate: number;
        };
        readonly GradeRateItem: {
            readonly grade: components["schemas"]["GradeSymbol"];
            readonly count: number;
            readonly rate: number;
        };
        readonly GradeDistribution: {
            readonly initial: readonly components["schemas"]["GradeRateItem"][];
            readonly final: readonly components["schemas"]["GradeRateItem"][];
        };
        readonly RiverStatistics: {
            readonly id: components["schemas"]["RiverId"];
            readonly name: string;
            readonly count: number;
            readonly rate: number;
            readonly missionSuccessRate: number;
            readonly perfectClearRate: number;
            readonly averageGradeImprovement: number;
            readonly gradeDistribution: components["schemas"]["GradeDistribution"];
            readonly policySelection: readonly components["schemas"]["RateItem"][];
        };
        readonly EventChoiceStatistics: {
            readonly id: components["schemas"]["EventChoiceId"];
            readonly name: string;
            readonly count: number;
            readonly rate: number;
        };
        readonly EventStatistics: {
            /** @enum {string} */
            readonly eventId: "DOWNSTREAM_ODOR_SURGE";
            readonly eligibleParticipants: number;
            readonly respondedParticipants: number;
            readonly responseRate: number;
            readonly choices: readonly components["schemas"]["EventChoiceStatistics"][];
            readonly sensorAssistedInvestigations: {
                readonly count: number;
                readonly rate: number;
            };
        };
        readonly CommentKeywordCategory: {
            /** @enum {string} */
            readonly id: "ODOR" | "POLLUTION_SOURCE" | "DATA_DISCLOSURE" | "ECOLOGY_RESTORATION" | "WALKING_AMENITIES" | "OTHER";
            readonly name: string;
            readonly count: number;
            readonly rate: number;
        };
        readonly CommentKeywordAnalysis: {
            readonly totalComments: number;
            /** @enum {string} */
            readonly classificationMode: "SINGLE_PRIMARY";
            readonly dictionaryVersion: string;
            readonly categories: readonly components["schemas"]["CommentKeywordCategory"][];
            readonly topCategories: readonly components["schemas"]["CommentKeywordCategory"][];
        };
        readonly CandidateComment: {
            /** Format: uuid */
            readonly id: string;
            readonly riverId: components["schemas"]["RiverId"];
            readonly riverName: string;
            readonly district: components["schemas"]["DistrictId"];
            readonly districtName: string;
            readonly topPriority: components["schemas"]["TopPriorityId"];
            readonly topPriorityName: string;
            readonly comment: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        readonly Statistics: {
            readonly totalParticipants: number;
            readonly todayParticipants: number;
            readonly missionSuccessRate: number;
            readonly perfectClearRate: number;
            readonly averageGradeImprovement: number;
            readonly gradeDistribution: components["schemas"]["GradeDistribution"];
            readonly riverParticipation: readonly components["schemas"]["RiverStatistics"][];
            readonly policySelection: readonly components["schemas"]["RateItem"][];
            readonly mostSelectedPolicy: components["schemas"]["RateItem"] | null;
            readonly topPriorities: readonly components["schemas"]["RateItem"][];
            readonly pledgeAreaSelection: readonly components["schemas"]["PledgeAreaRateItem"][];
            readonly eventStatistics: components["schemas"]["EventStatistics"];
            readonly commentKeywordAnalysis: components["schemas"]["CommentKeywordAnalysis"];
            readonly comments: readonly components["schemas"]["CandidateComment"][];
            /** @enum {boolean} */
            readonly isDemoData: true;
            readonly disclaimer: string;
        };
        readonly CandidateFilters: {
            readonly riverId: components["schemas"]["RiverId"] | null;
            readonly district: components["schemas"]["DistrictId"] | null;
            /** Format: date */
            readonly from: string | null;
            /** Format: date */
            readonly to: string | null;
        };
        readonly CandidatePeriod: {
            /** Format: date-time */
            readonly from: string | null;
            /** Format: date-time */
            readonly to: string | null;
        };
        readonly CandidateReportSummary: {
            readonly totalParticipants: number;
            readonly todayParticipants: number;
            readonly missionSuccessRate: number;
            readonly perfectClearRate: number;
            readonly averageGradeImprovement: number;
            readonly mostSelectedPolicy: components["schemas"]["RateItem"] | null;
        };
        readonly PrioritiesByRiver: {
            readonly riverId: components["schemas"]["RiverId"];
            readonly riverName: string;
            readonly totalParticipants: number;
            readonly priorities: readonly components["schemas"]["RateItem"][];
        };
        readonly PrioritiesByDistrict: {
            readonly district: components["schemas"]["DistrictId"];
            readonly districtName: string;
            readonly totalParticipants: number;
            readonly priorities: readonly components["schemas"]["RateItem"][];
        };
        readonly CandidateMethodology: {
            readonly participation: string;
            readonly rates: string;
            readonly representativeness: string;
            readonly commentKeywords: string;
            readonly prediction: string;
        };
        readonly CandidateReport: {
            readonly title: string;
            readonly period: components["schemas"]["CandidatePeriod"];
            readonly filters: components["schemas"]["CandidateFilters"];
            readonly summary: components["schemas"]["CandidateReportSummary"];
            readonly policySelection: readonly components["schemas"]["RateItem"][];
            readonly topPriorities: readonly components["schemas"]["RateItem"][];
            readonly pledgeAreaSelection: readonly components["schemas"]["PledgeAreaRateItem"][];
            readonly eventStatistics: components["schemas"]["EventStatistics"];
            readonly commentKeywordAnalysis: components["schemas"]["CommentKeywordAnalysis"];
            readonly perRiver: readonly components["schemas"]["RiverStatistics"][];
            readonly prioritiesByRiver: readonly components["schemas"]["PrioritiesByRiver"][];
            readonly prioritiesByDistrict: readonly components["schemas"]["PrioritiesByDistrict"][];
            readonly comments: readonly components["schemas"]["CandidateComment"][];
            readonly methodology: components["schemas"]["CandidateMethodology"];
            /** @enum {boolean} */
            readonly isDemoData: true;
        };
        readonly Pagination: {
            readonly page: number;
            readonly pageSize: number;
            readonly totalItems: number;
            readonly totalPages: number;
            readonly hasNext: boolean;
            readonly hasPrevious: boolean;
        };
        readonly CandidateCommentsPage: {
            readonly items: readonly components["schemas"]["CandidateComment"][];
            readonly pagination: components["schemas"]["Pagination"];
            /** @enum {string} */
            readonly sort: "latest" | "oldest";
            readonly filters: components["schemas"]["CandidateFilters"];
            /** @enum {boolean} */
            readonly isDemoData: true;
        };
    };
    responses: {
        /** @description 입력값 또는 JSON 본문 오류 */
        readonly ValidationError: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 공유 데이터베이스 일시 장애 */
        readonly DatabaseUnavailable: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 후보자 로그인이 필요하거나 세션이 만료됨 */
        readonly AuthenticationRequired: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 로그인한 계정에 후보자 대시보드 권한이 없음 */
        readonly AccessDenied: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 공유 데이터베이스 또는 인증 서비스의 일시 장애 */
        readonly ServiceUnavailable: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 지원하지 않는 HTTP 메서드 */
        readonly MethodNotAllowed: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 요청 본문 크기 제한 초과 */
        readonly PayloadTooLarge: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description application/json이 아닌 요청 */
        readonly UnsupportedMediaType: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 예상하지 못한 서버 오류 */
        readonly InternalServerError: {
            headers: {
                readonly "X-Request-ID": components["headers"]["RequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        readonly CandidateRiverId: components["schemas"]["RiverId"];
        readonly CandidateDistrict: components["schemas"]["DistrictId"];
        /** @description UTC 기준 시작일이며 해당 날짜를 포함합니다. */
        readonly CandidateFromDate: string;
        /** @description UTC 기준 종료일이며 해당 날짜를 포함합니다. */
        readonly CandidateToDate: string;
    };
    requestBodies: never;
    headers: {
        /** @description 서버 로그와 응답을 연결하는 요청 ID */
        readonly RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
